Repository lachieMiles/cryptoLab, pull requests merged in 2024-11, with the labels that each got.

#38 added auth.ts for middleware
  Develop/server/src/middleware/auth.ts
  README.md
Labels: backend

#43 initial CSS layout
  Develop/client/src/index.css
Labels: frontend

#41 Refactor Server and Seed Logic; Enhance README
  Develop/server/.env
  Develop/server/src/seeds/index.ts
  Develop/server/src/seeds/user-seeds.ts
  Develop/server/src/server.ts
  README.md
Labels: backend

#44 feat(controller): add getAllUsers controller for fetching user data
  Develop/server/src/controllers/user-controller.ts
Labels: backend

#45 Gateway to Server
  Develop/client/package-lock.json
  Develop/client/package.json
  Develop/client/src/api/authAPI.tsx
  Develop/client/src/api/userAPI.tsx
  Develop/client/src/interfaces/UserData.tsx
  Develop/client/src/interfaces/UserLogin.tsx
  Develop/client/src/pages/Login.tsx
  Develop/client/src/utils/auth.ts
  README.md
Labels: frontend

#51 Successfully implement user seeding functionality
  Develop/server/.env
  Develop/server/db/schema.sql
  Develop/server/src/config/connection.ts
  Develop/server/src/models/index.ts
  Develop/server/src/routes/auth-routes.ts
  Develop/server/src/routes/index.ts
  Develop/server/src/seeds/user-seeds.ts
  README.md
Labels: backend

#50 fixed duplicate code in main.tsx and app.tsx
  Develop/client/src/App.tsx
  Develop/client/src/main.tsx
Labels: frontend

#52 created dashboard page + table component
  Develop/client/src/components/Table.tsx
  Develop/client/src/interfaces/Crypto.tsx
  Develop/client/src/pages/Dashboard.tsx
  Develop/server/src/service/newsService.ts
Labels: frontend

#53 fix: resolve user seeding issues and enforce username validation
  Develop/server/src/models/user.ts
  Develop/server/src/seeds/user-seeds.ts
Labels: documentation, enhancement

#60 change table.tsx code
  Develop/client/src/components/Table.tsx
  Develop/client/src/index.css
  Develop/client/src/interfaces/Crypto.tsx
  Develop/client/src/main.tsx
  Develop/client/src/pages/Dashboard.tsx
  Develop/server/.env
  Develop/server/src/server.ts
Labels: bug

#62 newsCard edits
  Develop/client/src/assets/alien.png
  Develop/client/src/assets/moon-stars.png
  Develop/client/src/components/Card.tsx
  Develop/client/src/index.css
  Develop/client/src/pages/Dashboard.tsx
  Develop/server/package-lock.json
  Develop/server/package.json
  Develop/server/src/service/newsService.ts
Labels: frontend

#65 Responsive code
  Develop/client/src/assets/Frame 99.png
  Develop/client/src/assets/alien.png
  Develop/client/src/components/Card.tsx
  Develop/client/src/components/Navbar.tsx
  Develop/client/src/components/Table.tsx
  Develop/client/src/index.css
  Develop/client/src/pages/Login.tsx
  Develop/server/.env
Labels: frontend

#67 npm run seed
  Develop/package.json
Labels: bug
